# Generated by Django 6.0.8 on 2026-09-07 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('commission_rate', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_order_no', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned'), ('REJECTED', 'Rejected')], default='COMPLETED', max_length=20)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('net_settlement', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_order', to='sales.sale')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.platform')),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('delivery_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='delivery.deliveryorder')),
            ],
        ),
    ]
