# Generated by Django 5.2.17 on 2026-09-07 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('warehouse_type', models.CharField(choices=[('central', 'مركزي'), ('branch', 'فرعي')], default='central', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse', to='branches.branch')),
            ],
        ),
    ]
