# Generated by Django 6.0.8 on 2026-09-07 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_cash', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('actual_cash', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='closing', to='sales.shift')),
            ],
        ),
    ]
