# Generated by Django 6.0.8 on 2026-09-07 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_weight', models.DecimalField(decimal_places=3, max_digits=14)),
                ('cleaned_weight', models.DecimalField(decimal_places=3, max_digits=14)),
                ('difference', models.DecimalField(decimal_places=3, max_digits=14)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='processing', to='sales.saleitem')),
            ],
        ),
    ]
